version: "3.8"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    restart: unless-stopped
